name: Temperature Converter Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag temperature-converter:$(date +%s)

   - name: Up the container
     run: docker run -p 8069:8069 temperature-converter:latest

    - name: Run functional tests
      run: go test -v ./...
