name: Temperature Converter Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag temperature-converter:$(date +%s)

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Run functional tests
      run: docker run -d -p 8069:8069 temperature-converter
      run: go test -v ./...
      run: docker stop temperature-converter
